### ISSUE TITLE
make less verbose

### ISSUE THREAD

**Issue by macmanes** [jts/nanocorrect#3]
perhaps a `--quiet` option that sends a lot of the clustal stuff someplace other than the screen? The `pipeline.make` stuff is noisy, too.

**Comment by kthlnktng** [comment]
I second this notion. After running nanocorrect.py, my STDERR file was over 150k lines. It is difficult to parse out actual errors with a file this size.

**Comment by jts** [comment]
I've now fixed this in 9fbba13ebf2, sorry for the delay.

**Comment by kthlnktng** [comment]
Thanks, @jts!
