### ISSUE TITLE
error running HPCdaligner

### ISSUE THREAD

**Issue by bforde** [jts/nanocorrect#8]
Hi 
When I run nanocorrect-overlap.make I get the following error
perl ~/nanocorrect/nanocorrect-preprocess.pl ../Test_Npore_ReadsPass.2D.fasta > Test_2D.pp.fasta
~/bin/fasta2DB Test_2D Test_2D.pp.fasta
~/bin/DBsplit -s50 Test_2D
~/bin/DBdust Test_2D
HPCdaligner -t5 -mdust Test_2D > HPCcommands.txt
HPCdaligner: -m is an illegal option
make: **\* [HPCcommands.txt] Error 1

When I check the Usage for HPCdaligner I do not see and -m flag

Usage: HPCdaligner [-vbdAI] [-k<int(14)>] [-w<int(6)>] [-h<int(35)>] [-t<int>] [-H<int>]
                            [-e<double(.70)] [-l<int(1000)>] [-s<int(100)] [-M<int>]
                            [-dal<int(4)>] [-mrg<int(25)>]
                            path:db|dam [block:int[-range:int]

Is this a version issue

**Comment by nickloman** [comment]
Yes, it is - please update your DALIGNER to latest version, e.g. git pull and make
