### ISSUE TITLE
Please tag a stable release

### ISSUE THREAD

**Issue by sjackman** [jts/nanocorrect#9]
Two tags would be helpful.
- the version used for the paper [doi:10.1038/nmeth.3444](http://www.nature.com/nmeth/journal/vaop/ncurrent/full/nmeth.3444.html)
- the most current stable versions

**Comment by jts** [comment]
I've now tagged the version that we used in the paper, the subsequent commits are minor changes not worth tagging.

**Comment by sjackman** [comment]
Thanks!
